[build]
  command = "npm run build"
  publish = ".next"
  functions = "netlify/functions"
  command = "npm run build"
  publish = "public"


[functions]
  node_bundler = "esbuild"

[[plugins]]
package = "@netlify/plugin-inline-functions-env"
